# Generated by Django 2.1.7 on 2019-06-26 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GGAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GGGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GGGroupWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ggpoll.GGAnswer')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ggpoll.GGGroup')),
            ],
        ),
        migrations.CreateModel(
            name='GGQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GGUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('motto', models.CharField(max_length=300)),
                ('answers', models.ManyToManyField(to='ggpoll.GGAnswer')),
            ],
        ),
        migrations.AddField(
            model_name='gganswer',
            name='groups',
            field=models.ManyToManyField(through='ggpoll.GGGroupWeight', to='ggpoll.GGGroup'),
        ),
        migrations.AddField(
            model_name='gganswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ggpoll.GGQuestion'),
        ),
    ]
