# Generated by Django 2.1.7 on 2019-07-05 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ggpoll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gganswer',
            options={'verbose_name': 'Answer'},
        ),
        migrations.AlterModelOptions(
            name='gggroup',
            options={'verbose_name': 'God'},
        ),
        migrations.AlterModelOptions(
            name='ggquestion',
            options={'verbose_name': 'Poll Question'},
        ),
        migrations.AlterModelOptions(
            name='gguser',
            options={'verbose_name': 'Poll User'},
        ),
        migrations.RenameField(
            model_name='gganswer',
            old_name='choice_text',
            new_name='answer_text',
        ),
    ]
