# Generated by Django 2.1.7 on 2019-07-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggpoll', '0002_auto_20190704_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gggroupweight',
            name='weight',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=3),
        ),
    ]
